# Generated by Django 5.0.6 on 2024-05-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('idTipoPago', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('idTipoProd', models.AutoField(primary_key=True, serialize=False)),
                ('tipoProd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(default='No Especificado', max_length=45)),
                ('numeroTel', models.IntegerField(default=0)),
                ('correo', models.CharField(default='errno@especificado.com', max_length=45)),
                ('tipoPago', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(default='No Especificado', max_length=50)),
                ('valorUnitario', models.IntegerField(default=0)),
                ('numeroSerie', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('tipoProducto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tipoprod')),
                ('ubicacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
        ),
    ]
