# Generated by Django 5.0.6 on 2024-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_producto_categoria_producto_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('idKit', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('productos', models.ManyToManyField(related_name='kits', to='core.producto')),
            ],
        ),
    ]
